# Generated by Django 5.2.5 on 2025-08-31 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('on_learning', '0002_course_owner_lesson_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_sub', models.BooleanField(default=True, verbose_name='Статус подписки')),
                ('description', models.TextField(blank=True, max_length=150, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Добавлена')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменена')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='on_learning.course',
                                             verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['user'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
