name: Django CI/CD Pipeline

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install lint dependencies
        run: |
          poetry lock
          poetry install --no-root
      - name: Run Flake8
        run: poetry run flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: |
          poetry lock
          poetry install --no-root
      - name: Makemigrations
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          NAME: postgres
          USER: postgres
          PASSWORD: 123456
          HOST: localhost
          PORT: 5432
        run: poetry run python manage.py makemigrations
      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          NAME: postgres
          USER: postgres
          PASSWORD: 123456
          HOST: localhost
          PORT: 5432
        run: poetry run python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/feature/35.2-CI/CD_and_GitHub_Actions'
    env:
      SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
    steps:
      - name: Prepare SSH directory and key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Start ssh-agent and add key with passphrase
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          echo "echo \"$SSH_PASSPHRASE\"" > ~/.ssh/ssh_askpass
          chmod +x ~/.ssh/ssh_askpass
          DISPLAY=:0 SSH_ASKPASS=~/.ssh/ssh_askpass ssh-add ~/.ssh/id_ed25519
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Copy project files to server
        run: |
          ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << EOF
          DEPLOY_DIR="${{ secrets.DEPLOY_DIR }}"
          if [ ! -d "\$DEPLOY_DIR/.git" ]; then
            echo "Cloning repository into \$DEPLOY_DIR..."
            git clone "https://github.com/YURIi454/mod_30.1-33.git" "\$DEPLOY_DIR"
          fi
          cd "\$DEPLOY_DIR"
          git fetch origin
          git checkout "feature/35.2-CI/CD_and_GitHub_Actions"
          git reset --hard "origin/feature/35.2-CI/CD_and_GitHub_Actions"
          EOF
      - name: Install dependencies on server
        run: |
          ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
          cd "${{ secrets.DEPLOY_DIR }}"
          curl -sSL https://install.python-poetry.org | python3 -
          ~/.local/bin/poetry lock
          ~/.local/bin/poetry install --no-root
          EOF
      - name: Install and start Docker
        run: |
          ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          # Запуск Docker демона
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version
          echo "Application Docker installed"
          EOF
      - name: Create .env file on server
        run: |
          ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
          cd "${{ secrets.DEPLOY_DIR }}"
          cat > .env <<EOL
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          API_KEY_STRIPE=${{ secrets.API_KEY_STRIPE }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          HOST=db
          PORT=5432
          EOL
          EOF
      - name: Install and start Docker compose
        run: |
          ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
          cd "${{ secrets.DEPLOY_DIR }}"
          sudo docker compose down -v || true
          sudo docker compose up -d --build
          echo "Application started in background"
          EOF